
on: workflow_dispatch

name: Build the package

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.15.3'

    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.OS }}-node

    - name: Pin Yarn Version
      run: yarn set version 1.21.1
      
    - name: Setup Yarn
      run: yarn --frozen-lockfile setup

    - name: Install dependencies
      run: yarn --frozen-lockfile install
      
    - name: Build Tree
      run: yarn build
  
    - name: Populate Fusebit Profile
      run: mkdir -p ~/.fusebit/`cat ${FUSEBIT_STAGE_US_WEST_2} | jq -r '.keyPath'`
    - run: cat ${FUSEBIT_STAGE_US_WEST_2} | jq -r '.privateKey' > ~/.fusebit/`cat ${FUSEBIT_STAGE_US_WEST_2} | jq -r '.keyPath'`/pri
    - run: cat ${FUSEBIT_STAGE_US_WEST_2} | jq -r '.publicKey' > ~/.fusebit/`cat ${FUSEBIT_STAGE_US_WEST_2} | jq -r '.keyPath'`/pub
    - run: cat ${FUSEBIT_STAGE_US_WEST_2} | jq -r '.settings' > ~/.fusebit/settings.json
    
    - name: Test Fuse Function ls
      run: node cli/fusebit-cli/libc/index.js function ls
